import 'package:flutter/material.dart';
import 'package:nyc_parks/models/park.dart';
import 'package:nyc_parks/models/review.dart';
import 'package:nyc_parks/models/user.dart';
import 'package:nyc_parks/providers/park_provider.dart';
import 'package:nyc_parks/styles/styles.dart';
import 'package:nyc_parks/components/leaf_rating.dart';
import 'package:nyc_parks/components/user_icon.dart';
import 'package:provider/provider.dart';

// Date formatting generated by Cursor and Opus 4.5 AI
/// Formats a date string as relative time (e.g., "2 weeks ago")
String _formatRelativeTime(String? dateString) {
  if (dateString == null) return '';
  
  try {
    final date = DateTime.parse(dateString);
    final now = DateTime.now();
    final difference = now.difference(date);
    
    if (difference.inDays > 365) {
      final years = (difference.inDays / 365).floor();
      return years == 1 ? '1 year ago' : '$years years ago';
    } else if (difference.inDays > 30) {
      final months = (difference.inDays / 30).floor();
      return months == 1 ? '1 month ago' : '$months months ago';
    } else if (difference.inDays > 7) {
      final weeks = (difference.inDays / 7).floor();
      return weeks == 1 ? '1 week ago' : '$weeks weeks ago';
    } else if (difference.inDays > 0) {
      return difference.inDays == 1 ? '1 day ago' : '${difference.inDays} days ago';
    } else if (difference.inHours > 0) {
      return difference.inHours == 1 ? '1 hour ago' : '${difference.inHours} hours ago';
    } else {
      return 'Just now';
    }
  } catch (e) {
    return '';
  }
}

/// Formats a date string as "User since Month Year"
String _formatUserSince(String? dateString) {
  if (dateString == null) return '';
  
  try {
    final date = DateTime.parse(dateString);
    final months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return 'User since ${months[date.month - 1]} ${date.year}';
  } catch (e) {
    return '';
  }
}

/// A Google Maps-style review card with expandable text
/// Can show author info (on park page) or park info (on user page)
class ReviewCard extends StatefulWidget {
  final Review review;
  final VoidCallback? onAuthorTap;
  final int maxLines;
  
  /// For user page context - shows park name instead of author
  final String? parkName;
  final VoidCallback? onParkTap;
  final bool showAuthor;

  const ReviewCard({
    super.key,
    required this.review,
    this.onAuthorTap,
    this.maxLines = 7,
    this.parkName,
    this.onParkTap,
    this.showAuthor = true,
  });

  @override
  State<ReviewCard> createState() => _ReviewCardState();
}

class _ReviewCardState extends State<ReviewCard> {
  bool _isExpanded = false;
  bool _hasOverflow = false;

  @override
  Widget build(BuildContext context) {
    final review = widget.review;
    final author = review.author;
    final hasComments = review.comments != null && review.comments!.isNotEmpty;
    final isFriend = author.friendsWithLoggedInUser == true;
    final userSince = _formatUserSince(author.createdAt);
    final reviewDate = _formatRelativeTime(review.createdAt);

    return Container(
      padding: AppPadding.allMedium,
      color: Theme.of(context).colorScheme.surface,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header section - shows author OR park depending on context
          if (widget.showAuthor)
            _buildAuthorSection(author, userSince, isFriend)
          else if (widget.parkName != null)
            _buildParkSection(),

          const SizedBox(height: AppSizes.spacing12),

          // Rating, date, and favorite row
          Row(
            children: [
              LeafRating(rating: review.rating),
              if (reviewDate.isNotEmpty) ...[
                const SizedBox(width: AppSizes.spacing12),
                Text(
                  reviewDate,
                  style: AppTypography.bodySmall.copyWith(
                    color: AppColors.textSecondary,
                  ),
                ),
              ],
              if (review.favorite) ...[
                const SizedBox(width: AppSizes.spacing12),
                const Icon(
                  Icons.favorite,
                  size: 20,
                  color: AppColors.favorite,
                ),
              ],
            ],
          ),

          // Comments
          if (hasComments) ...[
            const SizedBox(height: AppSizes.spacing12),
            LayoutBuilder(
              builder: (context, constraints) {
                final textSpan = TextSpan(
                  text: review.comments,
                  style: AppTypography.bodyMedium,
                );
                final textPainter = TextPainter(
                  text: textSpan,
                  maxLines: widget.maxLines,
                  textDirection: TextDirection.ltr,
                )..layout(maxWidth: constraints.maxWidth);

                _hasOverflow = textPainter.didExceedMaxLines;

                return Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      review.comments!,
                      style: AppTypography.bodyMedium.copyWith(
                        color: AppColors.textPrimary,
                        height: 1.5,
                      ),
                      maxLines: _isExpanded ? null : widget.maxLines,
                      overflow: _isExpanded ? null : TextOverflow.ellipsis,
                    ),
                    if (_hasOverflow)
                      GestureDetector(
                        onTap: () => setState(() => _isExpanded = !_isExpanded),
                        child: Padding(
                          padding: const EdgeInsets.only(top: AppSizes.spacing8),
                          child: Text(
                            _isExpanded ? 'Show less' : 'Read more',
                            style: AppTypography.labelMedium.copyWith(
                              color: AppColors.primary,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ),
                  ],
                );
              },
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildAuthorSection(User author, String userSince, bool isFriend) {
    return GestureDetector(
      onTap: widget.onAuthorTap,
      behavior: HitTestBehavior.opaque,
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          UserIcon(
            user: author,
            iconSize: AppSizes.avatarMedium,
          ),
          const SizedBox(width: AppSizes.spacing12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  author.name,
                  style: AppTypography.titleLarge.copyWith(
                    color: AppColors.textPrimary,
                  ),
                ),
                const SizedBox(height: AppSizes.spacing4),
                Row(
                  children: [
                    if (userSince.isNotEmpty)
                      Text(
                        userSince,
                        style: AppTypography.bodySmall.copyWith(
                          color: AppColors.textSecondary,
                        ),
                      ),
                    if (isFriend) ...[
                      const SizedBox(width: AppSizes.spacing8),
                      Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: AppSizes.spacing8,
                          vertical: AppSizes.spacing2,
                        ),
                        decoration: BoxDecoration(
                          color: AppColors.success.withValues(alpha: 0.15),
                          borderRadius: AppBorderRadius.round,
                        ),
                        child: Text(
                          'Friend',
                          style: AppTypography.labelSmall.copyWith(
                            color: AppColors.success,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                    ],
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildParkSection() {
    final park = Provider.of<ParksProvider>(context, listen: false).parkFromGlobalId(widget.review.parkId);

    return GestureDetector(
      onTap: widget.onParkTap,
      behavior: HitTestBehavior.opaque,
      child: Row(
        children: [
          Container(
            width: AppSizes.avatarMedium,
            height: AppSizes.avatarMedium,
            decoration: BoxDecoration(
              color: AppColors.primaryLight.withValues(alpha: 0.2),
              borderRadius: AppBorderRadius.medium,
            ),
            child: Icon(
              park.typeCategoryIcon,
              color: AppColors.primary,
              size: 24,
            ),
          ),
          const SizedBox(width: AppSizes.spacing12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  widget.parkName ?? 'Unknown Park',
                  style: AppTypography.titleLarge.copyWith(
                    color: AppColors.textPrimary,
                  ),
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
                const SizedBox(height: AppSizes.spacing4),
                Text(
                  'Tap to view park',
                  style: AppTypography.bodySmall.copyWith(
                    color: AppColors.textSecondary,
                  ),
                ),
              ],
            ),
          ),
          const Icon(
            Icons.chevron_right,
            color: AppColors.textSecondary,
          ),
        ],
      ),
    );
  }
}

